### ISSUE TITLE
Cloudprints are not accepted

### ISSUE THREAD

**Issue by Fab7c4** [jaymoulin/docker-rpi-google-cloudprint#2]
Hey mate,
first of all thanks for your efforts. But I have some troubles getting it to work for me.
Opening cups and adding a printer works fine. Even adding it to my Google account. But it does not print. Printing a local test page from cups works. But Cloud prints are cancelled as I check CUPS:
```
HP_LaserJet_1320_series-4 	Unknown 	Withheld 	0k 	Unknown 	canceled at
Tue Sep 19 15:31:26 2017 	 
HP_LaserJet_1320_series-3 	Unknown 	Withheld 	0k 	Unknown 	canceled at
Tue Sep 19 15:26:48 2017 	 
HP_LaserJet_1320_series-2 	Unknown 	Withheld 	0k 	Unknown 	canceled at
Tue Sep 19 14:59:25 2017 	 
HP_LaserJet_1320_series-1 	Unknown 	Withheld 	0k 	Unknown 	canceled at
Tue Sep 19 14:59:18 2017
```
When I close the configuration the command does not exit cleanly and stays forever at the last printed line. I use CTR+C to get out there but I assume there is something going wrong which is why printing also does not work.
```
$ docker exec  cloudprint configure close
Polling for jobs on HP_LaserJet_1320_series
Establishing connection to xmpp server talk.google.com:5223
xmpp connection established
```
Any suggestions?

**Comment by jaymoulin** [comment]
Hello, First I need to know which image you used to check if everything is up. Then, Did you tried to print a test page via cups to check your printer was compatible with RaspberryPI?

**Comment by Fab7c4** [comment]
To the second question I can give you an answer. Printing test pages from CUPS works without problems. Regarding the image I just followed the instructions the same day and installed it as your README indicates. But if I can check somehow the version please let me know.

**Comment by jaymoulin** [comment]
You can check version using this command `docker images|grep jaymoulin/rpi-google-cloudprint`. 

If I'm correct, you'll see this :
`jaymoulin/rpi-google-cloudprint       latest              5f2f93d1c496        2 weeks ago         153MB`

There's probably a problem with my latest image, I suggest you you use version 0.1.2 while I try to fix the latest one with this command :

`docker run -d --privileged --restart=always -v /dev/bus/usb:/dev/bus/usb --name cloudprint -e CUPS_USER_ADMIN=admin -e CUPS_USER_PASSWORD=password -p 631:631 jaymoulin/rpi-google-cloudprint:0.1.2`

Tell me if it works better for you so I can check the latest version

**Comment by Fab7c4** [comment]
Hey @jaymoulin,
thanks for your help so with the image version 0.1.2 it works. Thanks for your help. Let me know if you think I can upgrade :-) . But for now this is fine for me like it is.
And true before I got exactly the output as you expected regarding the latest version.

**Comment by jaymoulin** [comment]
You may be able to update to 0.2.1 if you think this is relevant for you
