### ISSUE TITLE
Persistent config storage

### ISSUE THREAD

**Issue by a10kiloham** [jaymoulin/docker-rpi-google-cloudprint#4]
I was hoping to find an image that allowed a volume to store the config/state elsewhere so upgrades to the image don't overwrite my settings and require a new setup. Have you looked into that? Cheers for setting this up regardless!

**Comment by jaymoulin** [comment]
This is not documented but you can keep your configuration files if you mount those volumes :      `/root/` (file `.cloudprintauth.json`) and `/etc/cups`

**Comment by jaymoulin** [comment]
My last image didn't work as expected. you should be able to accomplish what you want to with version `0.4.0` and commands `configure save` and `configure load` as described in the README file.

**Comment by a10kiloham** [comment]
Thank you!
