### ISSUE TITLE
Installing additional print drivers

### ISSUE THREAD

**Issue by sanicki** [jaymoulin/docker-rpi-google-cloudprint#5]
I'm trying to use this with a [Brother MFC-9460CDN](http://support.brother.com/g/b/downloadtop.aspx?c=us_ot&lang=en&prod=mfc9460cdn_all) color laser printer.

I was able to `wget` the `.deb` files for the LPR printer driver and CUPSwrapper printer driver into the container, but can't run `dpkg` to install them:

```
sh: dpkg: not found
```

I also tried uploading the `.ppd` through the CUPS web interface, but then get:

```
Idle - "File "/usr/lib/cups/filter/brlpdwrappermfc9460cdn" not available: No such file or directory"
```

Is there a recommended way to install new print drivers?

**Comment by jaymoulin** [comment]
Because this image is based on an alpine release, you cannot be able to install it through dpkg without installing the tool to do that.

```bash
apk add dpkg --update --no-cache
```

You should be able to install your drivers then.

**Comment by HeXDeMoN** [comment]
More of a docker question I assume... but how do I install additional drivers? I want to run "sudo apt-get install printer-driver-splix" inside of the container but unsure how.

**Comment by jaymoulin** [comment]
This image is based on alpine so you won't be able to install splix.

FYI : 
The command would be `docker exec -ti cloudprint apt-get install printer-driver-splix` but for alpine you should use apk
`docker exec -ti cloudprint apk add printer-driver-splix`
