### ISSUE TITLE
Missing drivers

### ISSUE THREAD

**Issue by zackbcom** [jaymoulin/docker-rpi-google-cloudprint#6]
I have a Brother printer that I would like to use with this docker container.

What do you think would be the best way to add the drivers that I need to this container?

Should I create a dockerfile with FROM and reference yours and then add the needed drivers.

Thanks,

**Comment by jaymoulin** [comment]
You can either create your own image, adding your drivers to your existing container or mounting your specific drivers to a volume to a new container
